export const DEFAULT_WORKOUT = {
  Monday: [
    { exercise: 'Warmup (stretches)', reps: '15', sets: '1', rest: '30', notes: 'Neck/shoulder/tricep/chest/hip rotations' },
    { exercise: 'Bird Dog - Stability', reps: '15', sets: '1', rest: '30', notes: '' },
    { exercise: 'Warrior 1 - Yoga', reps: '10', sets: '1', rest: '30', notes: 'Hold 2-4s' },
    { exercise: 'Bulgarian Bag Side Swipe', reps: '15', sets: '3', rest: '30', notes: '' },
    { exercise: 'T-bar Rowing - Functional', reps: '12', sets: '3', rest: '60', notes: '' },
    { exercise: 'Wide Grip Pull Ups', reps: '5', sets: '3', rest: '60', notes: '' },
    { exercise: 'Lat Pull Down Wide Grip - Machine', reps: '12', sets: '3', rest: '30', notes: 'On Machine' },
    { exercise: 'Lat Pull Down Close Grip - Machine', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Bend Over Rowing Barbell', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Bend Over Dumbbell Row - Single Arm', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Chest Supported Dumbbell Rowing', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Dumbbell Reverse Fly', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Seated Cable Row - Machine', reps: '12', sets: '3', rest: '30', notes: '' },
  ],
  Tuesday: [
    { exercise: 'Warmup (stretches)', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Arm Circles - Flexibility', reps: '20', sets: '1', rest: '30', notes: '' },
    { exercise: 'Resistance Band Pull Apart', reps: '15', sets: '1', rest: '30', notes: '' },
    { exercise: 'Dead Bug - Core', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Tree Pose - Yoga', reps: '10', sets: '3', rest: '30', notes: '' },
    { exercise: 'Mudgal Lv1 - Crossfit', reps: '10', sets: '3', rest: '60', notes: '' },
    { exercise: 'High Knees - Cardio', reps: '25', sets: '3', rest: '90', notes: '' },
    { exercise: 'Burpees with Pushup', reps: '7', sets: '3', rest: '90', notes: '' },
    { exercise: 'Flat Bench Close Grip', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Tricep Push Down - Straight Rod', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Overhead Triceps Extension', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Skull Crushers', reps: '12', sets: '3', rest: '30', notes: '' },
  ],
  Wednesday: [
    { exercise: 'Warmup (stretches)', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Bird Dog - Stability', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Upward Facing Dog Pose', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Leg Raise - Core', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Russian Twist - Core', reps: '15', sets: '1', rest: '30', notes: '' },
    { exercise: 'Battle Rope - Cardio', reps: '10', sets: '3', rest: '30', notes: '' },
    { exercise: 'Bicep Curls (Dumbbells)', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Preacher Curl Machine', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Concentration Curl', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Hammer Curls', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Dumbbell Reverse Grip Bicep Curl', reps: '12', sets: '3', rest: '30', notes: '' },
  ],
  Thursday: [
    { exercise: 'Warmup (stretches)', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Single Leg Balance Reach - Yoga', reps: '10', sets: '3', rest: '30', notes: '' },
    { exercise: 'Mountain Climbers', reps: '25', sets: '3', rest: '60', notes: '25 each side' },
    { exercise: 'Skipping', reps: '30', sets: '3', rest: '60', notes: '' },
    { exercise: 'Push Ups', reps: '15', sets: '3', rest: '60', notes: '' },
    { exercise: 'Flat Bench', reps: '12', sets: '3', rest: '60', notes: '' },
    { exercise: 'Incline Bench Dumbbell Press', reps: '12', sets: '3', rest: '60', notes: '' },
    { exercise: 'Dumbbell Bench Press', reps: '12', sets: '3', rest: '60', notes: '' },
    { exercise: 'Decline Bench Press', reps: '12', sets: '3', rest: '60', notes: '' },
    { exercise: 'Butterfly', reps: '12', sets: '3', rest: '60', notes: '' },
  ],
  Friday: [
    { exercise: 'Warmup (stretches)', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Seated Forward Bend - Yoga', reps: '5', sets: '3', rest: '30', notes: 'Hold 5s' },
    { exercise: 'Flutter Kicks', reps: '30', sets: '1', rest: '30', notes: '' },
    { exercise: 'Hurdles Jump - Crossfit', reps: '20', sets: '1', rest: '30', notes: 'Two rounds in one set' },
    { exercise: 'Step Ups (Dumbbells)', reps: '20', sets: '3', rest: '90', notes: '' },
    { exercise: 'Jump Squats', reps: '15', sets: '3', rest: '90', notes: '' },
    { exercise: 'Lunges Forward', reps: '25', sets: '3', rest: '90', notes: '' },
    { exercise: 'Lunges Reverse', reps: '25', sets: '3', rest: '90', notes: '' },
    { exercise: 'Bulgarian Split Squats', reps: '25', sets: '3', rest: '90', notes: '' },
    { exercise: 'Squats On Barbell', reps: '15', sets: '3', rest: '90', notes: '' },
    { exercise: 'Dumbbell Squats', reps: '15', sets: '3', rest: '90', notes: '' },
    { exercise: 'Glute Bridge', reps: '15', sets: '3', rest: '90', notes: '' },
    { exercise: 'Hip Thrusts', reps: '15', sets: '3', rest: '90', notes: '' },
    { exercise: 'Leg Extension - Machine', reps: '15', sets: '3', rest: '90', notes: '' },
  ],
  Saturday: [
    { exercise: 'Warmup (stretches)', reps: '10', sets: '1', rest: '30', notes: '' },
    { exercise: 'Sitting Butterfly Stretch', reps: '25', sets: '1', rest: '30', notes: '' },
    { exercise: 'Cobra Stretch', reps: '15', sets: '1', rest: '30', notes: '' },
    { exercise: 'Mudhgal Level 2 - Crossfit', reps: '5', sets: '1', rest: '30', notes: '' },
    { exercise: 'Kettle Bell Swing', reps: '15', sets: '2', rest: '30', notes: '' },
    { exercise: 'Sled Push', reps: '10', sets: '2', rest: '30', notes: '15 kg or more' },
    { exercise: 'Frog Jumps', reps: '20', sets: '1', rest: '30', notes: '' },
    { exercise: 'Overhead Shoulder Press', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Side Lateral Raise', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Seated Dumbbell Press', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Upright Row - Shoulder', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Shrugs', reps: '12', sets: '3', rest: '30', notes: '' },
    { exercise: 'Face Pull - Functional', reps: '12', sets: '3', rest: '30', notes: '' },
  ],
  Sunday: [
    { exercise: 'Light Stretching', reps: '10-15 min', sets: '-', rest: '-', notes: 'Neck rolls, shoulder circles, hamstring stretches' },
    { exercise: 'Breathing / Yoga', reps: '10 min', sets: '-', rest: '-', notes: "Child's Pose, Cat-Cow" },
    { exercise: 'Walk / Mobility', reps: '20-30 min', sets: '-', rest: '-', notes: 'Light walk and joint rotations' },
    { exercise: 'Hydration + Nutrition', reps: '-', sets: '-', rest: '-', notes: 'Stay hydrated, protein-rich meals' },
    { exercise: 'Optional Core Stability', reps: '10 min', sets: '-', rest: '-', notes: 'Bird Dog or Plank' },
  ]
};
